# Generated by Django 5.0.3 on 2024-03-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_cargos_bairro_rename_tipos_imoveis_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='tipo_imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_imovel'),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro'),
        ),
    ]
