# Generated by Django 5.0.3 on 2024-03-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_imoveis_bairro_alter_imoveis_tipo_imovel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imoveis',
            new_name='imovel',
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name_plural': 'Imóveis'},
        ),
    ]
