# Generated by Django 5.0.3 on 2024-03-12 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_imoveis_imovel_alter_imovel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contrato_de_Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_do_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_de_locacao', to='app.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Contratos de Locação/Vendas',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='app.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locadores_imovel', to='app.imovel')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locador_pessoa', to='app.pessoa')),
                ('tipo_do_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locadores_tipo_imovel', to='app.tipo_imovel')),
            ],
            options={
                'verbose_name_plural': 'Locadores',
            },
        ),
    ]
