# Generated by Django 5.0.3 on 2024-03-13 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pessoa_telefone_contrato_de_locacao_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locador',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imovel'),
        ),
        migrations.AlterField(
            model_name='locador',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
        migrations.AlterField(
            model_name='locador',
            name='tipo_do_imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_imovel'),
        ),
    ]
