# Generated by Django 5.0.3 on 2024-03-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_locador_imovel_alter_locador_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatario',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
